using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using RentCar.Domain.Entities;

namespace RentCar.Application.Services
{
    public interface IContractPdfGenerator
    {
        string GenerateContractPdf(Reservation reservation, string outputDirectory = "contracts");
    }

    public class ContractPdfGenerator : IContractPdfGenerator
    {
        public string GenerateContractPdf(Reservation reservation, string outputDirectory = "contracts")
        {
            if (!Directory.Exists(outputDirectory))
                Directory.CreateDirectory(outputDirectory);

            string fileName = $"contract_reservation_{reservation.Id}_{DateTime.UtcNow.Ticks}.pdf";
            string filePath = Path.Combine(outputDirectory, fileName);

            Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Header().Text("Car Rental Contract").FontSize(20).Bold().AlignCenter();

                    page.Content().Column(col =>
                    {
                        col.Item().Text($"Contract Date: {DateTime.UtcNow:dd-MM-yyyy}");
                        col.Item().Text($"Reservation ID: {reservation.Id}");
                        col.Item().Text($"Business: {reservation.Business.CompanyName}");
                        col.Item().Text($"Client: {reservation.Client.FirstName} {reservation.Client.LastName}");
                        col.Item().Text($"Car: {reservation.Car.CarModel.Name} - {reservation.Car.LicensePlate}");
                        col.Item().Text($"Period: {reservation.StartDate:dd-MM-yyyy} to {reservation.EndDate:dd-MM-yyyy}");
                        col.Item().Text($"Total Price: {reservation.TotalPrice:C}");
                        col.Item().Text($"Status: Confirmed");
                        col.Item().LineHorizontal(1);
                        col.Item().Text("Terms & Conditions:").Bold();
                        col.Item().Text("1. The client is responsible for fuel costs.\n2. Any damage will be charged.\n3. Car must be returned on time.");
                    });

                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by RentCar System - ");
                        x.Span($"{DateTime.UtcNow:HH:mm:ss}");
                    });
                });
            })
            .GeneratePdf(filePath);

            return filePath;
        }
    }
}
